feat(unciae): warmup python programs with dedicated venv

diff --git a/.config/yadm/bootstraps/2_bootstrap_unciae b/.config/yadm/bootstraps/2_bootstrap_unciae
--- a/.config/yadm/bootstraps/2_bootstrap_unciae
+++ b/.config/yadm/bootstraps/2_bootstrap_unciae
@@ -32,6 +32,8 @@ find .local/share/unciae -type f -name "runner.*" | while read -r fname; do
 			uv pip install -r "${fname_req}"
 			echo -e "#!/bin/bash\n$(which python) \"${fname_abs}\" \$*" >"${fname_bin_path}"
 			deactivate
+			chmod a+x "${fname_bin_path}"
+			"${fname_bin_path}" --help >/dev/null 2>&1 || echo "${fname_bin} warmup failed"
 		else
 			echo "Linking Python script ${fname_bin} at ${fname_bin_path}"
 			ln -sf "${fname_bin_rel}" "${fname_bin_path}"
